# EXERCISE FOR NUMPY

In [6]:
mylist = [1,2,3,4,5]

In [7]:
mylist

[1, 2, 3, 4, 5]

In [8]:
import numpy as np

In [10]:
myoned = np.array(mylist)

In [11]:
myoned

array([1, 2, 3, 4, 5])

In [12]:
mytwolist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [14]:
mytwodarray = np.array(mytwolist)

In [16]:
mytwodarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#MATRIX OF ONE'S

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5,5)

array([[0.43978383, 0.96074024, 0.39702802, 0.76142563, 0.72758777],
       [0.3172545 , 0.23171664, 0.64694853, 0.07588275, 0.82485856],
       [0.02404235, 0.75909403, 0.09338955, 0.92265478, 0.59765015],
       [0.70595563, 0.33962093, 0.50382666, 0.15263732, 0.27626798],
       [0.21550525, 0.96560346, 0.30392867, 0.54970584, 0.61079202]])

In [30]:
np.random.randn(3,3)

array([[ 0.41491712, -1.02599243, -0.749731  ],
       [ 0.49941169, -0.25951675, -0.24847572],
       [ 0.58821487,  1.11056499,  0.42420535]])

In [31]:
np.random.randint(1,50)

17

In [39]:
myNum = np.arange(25)

In [40]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
myreshaped = myNum.reshape(5,5)

In [44]:
myreshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
myreshaped.max

<function ndarray.max>

In [46]:
myreshaped.min

<function ndarray.min>

In [47]:
pwd

'C:\\Users\\ADMIN'