In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,25,1.5)

array([ 5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. , 18.5, 20. ,
       21.5, 23. , 24.5])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(5,5)

array([[0.25210875, 0.17052204, 0.42611196, 0.73691124, 0.02631238],
       [0.23314582, 0.67577547, 0.75081115, 0.34225569, 0.89819732],
       [0.30322335, 0.52775365, 0.6187353 , 0.44094245, 0.13516457],
       [0.80030428, 0.04067148, 0.10600134, 0.80613622, 0.76522242],
       [0.75123913, 0.76567513, 0.06581973, 0.04707015, 0.82340252]])

In [13]:
np.random.randint(1,100)

64

In [14]:
arr = np.arange(25)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ranarr = np.random.randint(0,50,10)

In [17]:
ranarr

array([32, 13, 13,  2, 33, 31, 49, 24, 35, 12])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr

array([32, 13, 13,  2, 33, 31, 49, 24, 35, 12])

In [20]:
ranarr.max()

49

In [21]:
ranarr.argmax()

6

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
np.zeros(shape = [2,1],dtype='int32')

array([[0],
       [0]])

##array indexing

In [24]:
import numpy as np

In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[8]

8

In [28]:
arr[1:5]

array([1, 2, 3, 4])

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5] = 10

In [31]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [32]:
slice_of_arr = arr[5:8]

In [33]:
slice_of_arr

array([5, 6, 7])

In [34]:
slice_of_arr[:] = 99

In [35]:
slice_of_arr

array([99, 99, 99])

In [36]:
arr_copy = arr.copy()

In [37]:
arr

array([10, 10, 10, 10, 10, 99, 99, 99,  8,  9, 10])

In [38]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr_2d[2][2]

9

In [41]:
arr_2d[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr>=5

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
arr_2d = np.arange(50).reshape(5,10)

In [46]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

ARRAY WITH ARRAY

In [47]:
import numpy as np

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
arr/arr

C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# UNIVERSAL FUNCTIONS

In [52]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [53]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [54]:
np.max(arr)

10

In [55]:
np.log(arr)

C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [56]:
np.array([10,3,4,5,6,7,8,9])

array([10,  3,  4,  5,  6,  7,  8,  9])

In [57]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
'GREAT JOB'

'GREAT JOB'